name: Terraform Prod Pipeline

on:
  push:
    branches:
      - prod

jobs:
  terraform:
    name: Terraform Apply - Prod
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://console.aws.amazon.com

    defaults:
      run:
        working-directory: environments/prod

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
